---
title: "Covid_microbiome"
output: html_document
---

#Set up
```{r setup, include=FALSE,echo=FALSE, warning=FALSE, results='hide', message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

 # this script loads the packages and installing them if needed
source("scripts/load_packages.R")

 # this script loads the functions into the space
source("scripts/my_scripts.R")

# Loads the local curated data if the data is not there then it will download it 
source("scripts/get_curatData.R")

```

#User defined variables
```{r, include=FALSE,echo=FALSE, warning=FALSE, results='hide', message=FALSE}
# These are go point for the analysis that takes the longest
beta.go <- TRUE
siamcat.go <- TRUE
# Label prefix for PDF that are generated
#labels editing of files
output.prefix <- "output/Covid19_"
#############################################
# Filtering of the curat dataset

# All of the pseq that are ever generated are stored within the mypseq. 
mypseq <- list("raw.curat.pseq" = curat.pseq)
############################################
# define the year and the age
gbd.year <-"2020"
gbd.age <- "aged 70 or older"
# set colour theme
theme_set(theme_Sharmalab())         
# Data input
# Input the Our World in Data
# Covid data set
data_hosp <- read.csv("~/Desktop/Covid_Curat.csv")
# AD Range of the graphs
hosp.range <- c(3416,5984109)

#### THIS IS THE HIGH AND LOW GROUPS THAT WILL BE USED THROUGHOUT THE SCRIPT 
# loads the Our World in Data and relabels straight away. 
covid.owid <- as.data.frame(data_hosp, col_names = TRUE) %>%
  rename_all( tolower)  %>%
  dplyr::select(location, hosp_patients)

# Covid groupings
curat.low <- c("FIN","USA","CAN","DNK","AUT","EST","NLD")
curat.high <- c("ESP", "ISR", "SWE", "SLV", "GBR", "FRA", "ITA") 
# this are the countries that are dropped.
curat.drop <- c("BGD","ETH", "GHA", "HUN", "ISL", "LUX", "NOR", "SVK", "DEU", "FJI", "KAZ", "MDG", "CHN", "MNG", "PER", "RUS", "TZA", "IND")

mythres <- 1848.58

# Figure legends
disease <- "COVID-19"

# define the labels for the graphs generated
hosp.label <- "Hospitalised Patients on a given day"
grp.label <-"Disease group"
fig_title_gbm_combo <- "Figure 1"
fig_title_gbm_mgnify <- "Disease burden represented in the Curated microbiome data" 
fig_title_alpha <- "Alpha Diversity for the Curated dataset"
fig_title_beta <- "Beta Diversity for the Curated dataset"
fig_title_abudance <- 'Abundance in the disease grouping in Curated microbiome dataset'
fig_title_permanova <- "PERMANOVA"
tab_title_gbm <- paste('Burden of ', disease)
gbm_ref <- "Our World in Data Study, 2020"
```

# Main processing scripts
```{r,include=FALSE,echo=FALSE, warning=FALSE, results='hide', message=FALSE}
# runs the country prep script 
# no pseq used
# runs the pseq recode script 
#source("scripts/pseq_recode.R")
# CURATED DATA SET
# grabs the nationality from phyloseq
curat.covid.class <- get_variable(curat.pseq, "country" )
curat.covid.class <- fct_collapse(curat.covid.class, LOW = curat.low , HIGH = curat.high)
# reorder
curat.covid.class <- factor(curat.covid.class, levels = (c("LOW", "HIGH")))
# creates a CURATE COVID CLASS in the phyloseq 
sample_data(curat.pseq)$curat.covid.class = curat.covid.class
# dropping the other countries
country <- get_variable(curat.pseq, "country" )
country <- droplevels(factor(country), curat.drop) 
sample_data(curat.pseq)$country = country

# important to subset the data else it adds all of the ages up together
#a <- aggregate(Hosp_patients, subset(covid.owid.sub, age == gbd.age), mean)
#covid.owid.gg <- a
curatcountry <- as.data.frame(table(get_variable(curat.pseq, "country")))

curat.combined <- covid.owid

# RECODING OF VARIABLES 
# creates a grouping variable for BMI
n <- length(sample_data(curat.pseq)$BMI)
data <- data.frame(id=1:n)
data$bmi <- sample_data(curat.pseq)$BMI # creates a new variable with BMI in it
# Classification based upon the ATlas data
data$bmi[data$bmi <18.5] <- "underweight"
data$bmi[data$bmi >=45] <- "super obese"
data$bmi[data$bmi >= 18.5 & data$bmi <25] <- "lean"
data$bmi[data$bmi >= 25 & data$bmi <30] <- "overweight"
data$bmi[data$bmi >= 30 & data$bmi <35] <- "obese"
data$bmi[data$bmi >= 35 & data$bmi <40] <- "severe obese"
data$bmi[data$bmi >= 40 & data$bmi <45] <- "morbid obese"
data$bmi <- factor(data$bmi)    

# creates a new variable in the phyloseq called BMI
sample_data(curat.pseq)$bmi_group = data$bmi
# Check that it works
#get_variable(pseq, "bmi_group")


# same with gender -> sex
# creates a grouping varaible for BMI
n <- length(sample_data(curat.pseq)$gender)
data <- data.frame(id=1:n)
data$sex <- sample_data(curat.pseq)$gender # creates a new variable with gender in it
# Classification based upon the ATlas data
data$sex[data$sex == "female"] <- "female"
data$sex[data$sex == "male"] <- "male"
data$sex <- factor(data$sex)

# creates a new variable in the phyloseq called sex
sample_data(curat.pseq)$sex = data$sex

data <- data.frame(id=1:n)

mypseq[["curat.recode.pseq"]] <- curat.pseq

# Common variables to keep:  "age", "sex", "nationality", "bmi_group", "subject/subjectID", "mnd"
# sample_variables(pseq)
# sample_data(pseq)[c(2:16,18:96)] = NULL
# 

# runs the pseq prep script # The output is; curat.combined.agestd & atlas.curat.combined.agestd
# curat.pseq & atlas.pseq that contains curat2atlas.mnd.class,curat.mnd.class &  atlas.mnd.class
#source("scripts/pseq_prep.R")
pseq_prep_1 <- function(curat.pseq,mypseq) {
 
  # This script loads and then generates the dataframe required later on. 
  # It uses the classification from the main script. 
  # The output is; curat.combined.agestd & atlas.curat.combined.agestd
  # curat.pseq & atlas.pseq that contains curat2atlas.mnd.class,curat.mnd.class &  atlas.mnd.class
  
  # INPUTs
  # curat.pseq
  # atlas.pseq
  
  # OUTPUTS
  
  # atlas.pseq
  # atlas.curat.combined.agestd
  #"curat.pseq
  #"curat.combined.agestd
  # curat.combined
  
  
  # Cleaning up the Taxa
  message("Cleaning up the taxa")
  taxa_names(curat.pseq) <- str_remove(taxa_names(curat.pseq), "s__")
  taxa_names(curat.pseq) <- str_replace(taxa_names(curat.pseq), "_", " ")


  # CURATED DATA SET
  message("Working on the Curat data ")
  # grabs the nationality from phyloseq
  curat.covid.class <- get_variable(curat.pseq, "country" )
  curat.covid.class <- fct_collapse(curat.covid.class, LOW = curat.low , HIGH = curat.high)
  # reorder
  curat.covid.class <- factor(curat.covid.class, levels = (c("LOW", "HIGH")))
  # creates a CURATE COVID CLASS in the phyloseq 
  sample_data(curat.pseq)$curat.covid.class = curat.covid.class
  message("Writing the countries into the Curat data")
  
  # dropping the other countries
  country <- get_variable(curat.pseq, "country" )
  country <- droplevels(factor(country), curat.drop) 
  sample_data(curat.pseq)$country = country

  # expected output
  #atlas.mnd.class 
  
  #curat.mnd.class
  # curat2atlas
  
  # table(get_variable(atlas.pseq, "atlas.mnd.class"))
  # table(get_variable(curat.pseq, "curat2atlas.mnd.class"))
  # table(get_variable(curat.pseq, "curat.mnd.class"))
  # table(get_variable(curat.pseq, "curat2atlas"))
  # table(get_variable(curat.pseq, "country"))
  # table(get_variable(atlas.pseq, "country"))
  # 
  # 
  
  
mypseq[["curat.recode.country.pseq"]] <- curat.pseq

message("Returning a list called mypseq \n that contains: \n curat.recode.country.pseq ")

return(mypseq)
}
mypseq <- pseq_prep_1(curat.pseq,mypseq)

mydata_prep <- function(mypseq) {

  # this accepts the list from the pseq_prep_2
  message("The pseq being used are: \n curat.recode.country.pseq ")  
  curatcountry <- as.data.frame(table(get_variable( mypseq[["curat.recode.country.pseq"]], "curatcountry")))
  
  #####################
  
  #this add the number of microbiome for each group
  # renames the columns so that they match
  atlascountry <- atlascountry %>% dplyr::rename(atlas.freq = Freq, Region = Var1 )
  mnd.gbd.gg <- left_join(mnd.gbd.gg, atlascountry)
  
  curat2atlas <- curat2atlas %>% dplyr::rename(Region = Var1,curat.atlas.freq = Freq )
  mnd.gbd.gg <- left_join(mnd.gbd.gg, curat2atlas)
  #####################
 
  mydata <- list("curat.combined.agestd" = curat.combined.agestd,
                 "curat.combined" = curat.combined)
  message("Returning mydata that contains:\n curat.combined.agestd \n curat.combined ")
  
  return(mydata)

}
mydata <- mydata_prep(mypseq)
# output  atlas.pseq, atlas.curat.combined.agestd, curat.pseq, curat.combined.agestd, curat.combined)

# test


mypseq <- pseq_filter(mypseq)

list2env(mypseq,envir=.GlobalEnv)
list2env(mydata,envir=.GlobalEnv)

```

\newpage
#Table Global Burden of Disease
```{r, message=FALSE, warning=FALSE, echo=FALSE}
# ad.gbd.sub data is the output from the country_prep.R script 
my.table.data <- ad.gbd.sub
# creates the data.frame from the GBD table based on year and age
my.table.data <- my.table.data[my.table.data$year == gbd.year & my.table.data$age == gbd.age , ]
# removes other columns
my.table.data <- dplyr::select (my.table.data, "location", "Prevalence", "Incidence", "DALY")
# gbm.table is a Sharmalab function. expects the levels. This produces the table in flextable format
gbm.table <- function(my.table.data,gbm.mean.levels) {
  ft <-arrange(my.table.data, location)
  ft <-ft %>% dplyr::rename(location = location)
  ft <- flextable(ft) %>% 
    footnote( i = 1, j = 2:4,
              value = as_paragraph(
                c(gbm_ref)
              ),
              ref_symbols = c("a"),
              part = "header") %>% 
    colformat_num( j = 3:4, digits = 2) %>% 
    valign( valign = "bottom", part = "header") %>% 
    add_header_lines(values = c(tab_title_gbm) ) %>% 
    bold(part = "header") %>%
    theme_booktabs() %>% 
    autofit() %>% 
    fix_border_issues()
  return(ft)
}
ft <- gbm.table(my.table.data) 
ft
```