```{r setup, include=FALSE,echo=FALSE, warning=FALSE, results='hide', message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

 # this script loads the packages and installing them if needed
source("scripts/load_packages.R")

 # this script loads the functions into the space
source("scripts/my_scripts.R")

# Loads the local curated data if the data is not there then it will download it 
source("scripts/Oral_PD_MGnify_Downloads.R")

# Loads dataset
oral.pseq <- data(complete_psobj)

```

#User defined variables
```{r, include=FALSE,echo=FALSE, warning=FALSE, results='hide', message=FALSE}

# This is the block that should be edited. The rest should work. 


# These are go point for the analysis that takes the longest
beta.go <- TRUE
siamcat.go <- TRUE

# Label prefix for PDF that are generated
#labels editing of files
output.prefix <- "output/oral_PD_"

# define the year and the age
gbd.year <-"2017"
gbd.age <- "Age-standardized"

# set colour theme
theme_set(theme_Sharmalab())         

# Data input

# Input the Global Burden of Disease data
data_daly <- 'data/PD-DA-B.csv'
data_prev <- "data/PD-P-B.csv"
data_incid <- "data/PD-I-B.csv"


# PD Range of the graphs. This is really important for the tile graphs. The figures are the range of each part. 
daly.range <- c(50,80)
prev.range <- c(70,170)
incid.range <- c(9,17)


#### THIS IS THE HIGH AND LOW GROUPS THAT WILL BE USED THROUGHOUT THE SCRIPT If this is the first time then keep these value for the moment


#PD grouping
oral.low <- c("Japan", "Italy", "United States", "Austria", "Switzerland")
oral.high <- c("United Kingdom","China","Taiwan", "Philippines", "Brazil") 

mythres <- 100

# Figure legends
disease <- "PD"

# define the labels for the graphs generated
mnd.prev.label <- "Prevalence \n(per 100,000)"
mnd.incid.label <- "Incidence \n(per 100,000)"
mnd.daly.label <- "DALY rate\n(per 100,000)"
grp.label <-"Disease group"

fig_title_gbm_oral <- "Figure 1: Disease burden for Regions represented in Oral microbiome data"
fig_title_alpha <- "Alpha Diversity for the Oral dataset"
fig_title_beta <- "Beta Diversity for the Oral dataset"
fig_title_abundance <- 'Abundance in the disease grouping in Oral microbiome dataset'
fig_title_permanova <- "PERMANOVA"

tab_title_gbm <- paste('Burden of ', disease)
gbm_ref <- "Lancet 2016"

```

# Main processing scripts
```{r,include=FALSE,echo=FALSE, warning=FALSE, results='hide', message=FALSE}
# runs the country prep script 
# no pseq used
source("scripts/Oral_PD_MGnify_country_prep.R")


# runs the pseq recode script 
source("scripts/pseq_recode.R")


# runs the pseq prep script # The output is; curat.combined.agestd & atlas.curat.combined.agestd
# curat.pseq & atlas.pseq that contains curat2atlas.mnd.class,curat.mnd.class &  atlas.mnd.class
#source("scripts/pseq_prep.R")

mypseq <- pseq_prep_1(atlas.pseq, curat.pseq,mypseq)

mydata <- mydata_prep(mypseq)
# output  atlas.pseq, atlas.curat.combined.agestd, curat.pseq, curat.combined.agestd, curat.combined)

# test


mypseq <- pseq_filter(mypseq)

list2env(mypseq,envir=.GlobalEnv)
list2env(mydata,envir=.GlobalEnv)

```